const nsfwmenu = (prefix, pushname) => {
    return `「꧁꧅ᏒꂅguᏒuᏕ꧅꧂」 
                      「B⃟O⃟T⃟*」


༻══ •『𝐈 𝐌 𝐏 𝐎 𝐑 𝐓 𝐀 𝐍 𝐓 𝐄 』• ══༺
➪𝑩𝑶𝑻 𝑻𝑹𝑨𝑫𝑼𝒁𝑰𝑫𝑶 𝑷𝑶𝑹 :
@k1r1t0_edits & @otaku.exp
➪𝑴𝑬𝑼 𝒀𝑶𝑼𝑻𝑼𝑩𝑬 :
https://youtube.com/channel/UCz0zX7CX5V4RsFKB8lncYRQ
➪𝑩𝑶𝑻 𝑪𝑹𝑰𝑨𝑫𝑶 𝑷𝑨𝑹𝑨 𝑬𝑵𝑻𝑹𝑬𝑻𝑬𝑵𝑰𝑴𝑬𝑵𝑻𝑶 .
➪PARA ADICIONAR O BOT EM UM GRUPO, MANDE UMA MENSAGEM NO NÚMERO ABAIXO:
wa.me/+5544999862424

*╔═══✤ •ೋ°۝°ೋ•✤ ═══╗*
> ${prefix}randomhentaio
> ${prefix}nsfwbobs
> ${prefix}nsfwtrap
> ${prefix}nsfwass
> ${prefix}nsfwahegao
> ${prefix}nsfwfeets
*╚═══✤ •ೋ°۝°ೋ•✤ ═══╝*

*𝑵 𝑶 𝑻 𝑨 *
_ᴀʟɢᴜɴs ᴄᴏᴍᴀɴᴅᴏs ᴘᴏᴅᴇᴍ ɴᴀᴏ ᴇsᴛᴀʀ ғᴜɴᴄɪᴏɴᴀɴᴅᴏ, sᴇ ɴᴀᴏ ɢᴏsᴛᴀʀ É sɪᴍᴘʟᴇs, ɴᴀᴏ ᴜsᴇ_
`



}

exports.nsfwmenu = nsfwmenu
